name: Lint practice
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get dependencies
        run: npm i
      - name: Lint code
        run: npm run lint 
      - name: Run tests      
        run: npm test  
      - name: Build application      
        run: npm run build
      - name: Deploy code
        run: echo "Fake deploy..."